global:
  scrape_interval:     15s
  evaluation_interval: 11s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
- job_name: 'statsd_exporter'
  scrape_interval: 5s
  static_configs:
    - targets: ['statsd_exporter:9102']